name: envy_generator
description: Code generation for extracting environment variables 
version: 0.0.5
homepage: https://github.com/ksokolovskyi/envy

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  analyzer: "^6.0.0"
  build: ^2.0.0
  dotenv: ^4.0.1
  envy_annotation: ^0.0.3
  recase: ^4.0.0
  source_gen: ^1.2.0

dev_dependencies:
  source_gen_test: ^1.0.2
  test: ^1.21.0
